### ISSUE TITLE
How to add geo_cost without any depth info?

### ISSUE THREAD

**Issue by ahangchen** [weixk2015/DeepSFM#1]
in PSNet, if add_geo is open, targets_depth is used to calculate some costs, but how to add geo cost when I don't have any depth info? can I init target depth with zero matrix?

**Comment by weixk2015** [comment]
Initializing target depth with zero matrix may cause a performance decay. By the way, unfortunately, if add_geo is turned off, the channels in the network will change and the pretrained model will not be loaded properly, so the network needs to be retrained. If there are initial camera poses, you can run DPSNet or other MVS methods to get initial depth maps. If no camera poses are given, I suggest you to run DeMoN to generate initial camera poses and depths.

**Comment by weixk2015** [comment]
> in PSNet, if add_geo is open, targets_depth is used to calculate some costs, but how to add geo cost when I don't have any depth info? can I init target depth with zero matrix?

**Comment by ahangchen** [comment]
Did you generate inital depth with depthnet without add_geo? Could you provide a pretrained model without geo?

**Comment by weixk2015** [comment]
> Did you generate inital depth by your depthnet without add_geo? Could you provide a pretrained model without geo?

I didn't do that, and the initial depth is generated via DeMoN. Meanwhile, the structure of depthnet is identical to DPSNet without add_geo, so the pretrained model from DPSNet can be loaded. I didn't retrain the depthnet without geo.

**Comment by ahangchen** [comment]
Got it, thank you very much.
