### ISSUE TITLE
Question about models/PoseNet and iterations

### ISSUE THREAD

**Issue by chouscode** [weixk2015/DeepSFM#3]
Hi, Good job and congratulations for the oral in ECCV 2020. 
Im new here and had tried to use your scripts for testing the test-datasets. However, I was troubled for some questions and problems. Can you help me solve the followings if you are free? THX.

1. What's the meaning of outputs for PoseNet? In your script `pose_test.py`, the outputs of PoseNet are then transformed to the value `p_matrix`. So, what is the meaning of this value? Is this value meaning the variation of relative pose matrix(`noise_pose` in your codes) ?

2. In your script `pose_test.py`,  what you saved in '%{args}_poses,txt' is the relative pose matrix between target and reference images. Is that right? However，we should read the absolute pose of each image from the last '%{args}_poses,txt'. There seems to be a conflict between the two files.

3. When I tried to use the `poses.txt` as the initial pose(Not the demon outputs) for the iterations testing, the results are getting worse. I think there may be something wrong with the saved pose file(maybe every iteration, the codes saved wrong pose). Have you ever been in this situation？

I would appreciate it if you could answer these questions! THX

**Comment by weixk2015** [comment]
Thanks. Here are some clarifications:
1. p_trans are the scores of sampled translations and trans_c are the sampled translations. The predicted trans and rots are computed via softmax according to the scores. Then they are turned into R|t matrix, which are the variation of relative pose. Then it is multiplied by the initial noise pose(relative pose).  
2. In my experiments with DeMoN initialization, the pose of the first frame is set to identical matrix, to turn the relative value into absolute pose, and no conflicts are found.
3. I think you are right. Seems there are bugs if the 'pose.txt' is adopted as initialization file. I didn't go into that situation before. I will figure out that when I have some free time. THX.

**Comment by chouscode** [comment]
Thanks for your quickly reply and answers.
The first question is cleared for me (THX for your answers.). However, Im still have some troubles about the socond one, although you have explained well. If the pose of the first frame is set to identical matrix, of course, the relative pose is consistent with the absolute one. But for the second iteration, what I read from the last `f'{args.save}_poses.txt`, for example `I0_poses.txt` in 2-paris-images MVS test-datasets, is the real absolute pose for the first image (NOT identical matrix) and the relative pose between the first and the second.  So, the `noise_pose` which calculated from the two poses matrix in last `f'{args.save}_poses.txt` may be incorrect in next iteration. Is that right? This may be the trouble what i go into in the iteration testing.

**Comment by weixk2015** [comment]
Thanks, I agree with you that the implementation has some defects.  In the test case, since each scene has two sequence, and the predicted poses are saved only once, the result will be correct if the pose of the first frame is identical. On that situation, only the result of the second frame is updated and the pose of the first frame stays identical, so the results will be correct during iterations. The implementation will be incorrect if the pose of the first frame is not identical. THX for you to point that out.

**Comment by chouscode** [comment]
Thanks for your reply. 
I tried to fix the codes of `f'{args.save}_poses.txt` to save the two absolute pose of the two images, using the matrix multiplication. It works! The iteration are getting slightly worse, which maybe coused by the initial pose. I have planned to use the DeMon results as the initial pose for trying. Good luck!
