### ISSUE TITLE
Visualization Method

### ISSUE THREAD

**Issue by jytime** [weixk2015/DeepSFM#5]
Hi Xingkui,

Hope you are doing well. I was wondering how did you plot depth maps for DEMON datasets, as in your paper. Is it 

plt.imshow(depth_np, cmap='Greys')

Best,
Jianyuan

**Comment by weixk2015** [comment]
Thanks, the visualization methods are borrowed from [SfmLearner-Pytorch](https://github.com/ClementPinard/SfmLearner-Pytorch/blob/ae63049a95ec35bfaccce67142d1ae381c484389/utils.py#L86) and [DPSNet](https://github.com/sunghoonim/DPSNet/blob/master/utils.py#L32). The depth maps are scaled to a predefined color space(gray or rainbow) to visualize.

**Comment by jytime** [comment]
Thanks
