### ISSUE TITLE
where to download demon_poses.txt and *_demon.npy

### ISSUE THREAD

**Issue by zwxu064** [weixk2015/DeepSFM#6]
Hi, could you let me know where to download demon_poses.txt and *_demon.npy? I checked https://github.com/lmb-freiburg/demon, but I did not find the way.

Thanks.

**Comment by weixk2015** [comment]
To get demon_poses.txt and *_demon.npy, you need to run DeMoN for depth and motion prediction and copy the depth results as *_demon.npy and write the pose results in demon_poses.txt respectively.

**Comment by zwxu064** [comment]
Thank you.

**Comment by ShichenLiu** [comment]
Hi, it seems that the DeMoN evaluation only outputs the depth map for the first image. Could you elaborate on how to generate the depth map for the second image? e.g. by simply swapping the input image pair or by warping the flow?
